pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh '''
				dotnet restore Jenkins.csproj
				dotnet build Jenkins.csproj
				'''
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
